### PR TITLE
.github: add check for chinese punctuation

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

### CODE REVIEW

**Comment by ran-huang** [comment]
@CharLotteiu PTAL. Thanks~

**Comment by tisonkun** [comment]
Hi @ran-huang ! May we later delete the `.circleci` folder?

**Comment by ran-huang** [comment]
> Hi @ran-huang ! May we later delete the `.circleci` folder?

@YiniXu9506 PTAL~

**Review by CharLotteiu — APPROVED** [review]
LGTM

**Pull request merged**
